### ISSUE TITLE
NPM Package does not include built files

### ISSUE THREAD

**Issue by anguspiv** [PreciselyData/PreciselyAPIsSDK-NodeJS#2]
Installed the package via npm `npm install preciselyapis-client` 

when we tried to run the node script we would get this error:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'preciselyapis-client'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'preciselyapis-client'",
        "Require stack:",
        "- /var/task/app.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
        "    at Module.load (internal/modules/cjs/loader.js:985:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

after debugging we noticed that `package.json` has main pointing to `api.js` but that file is not included as part of the npm package. 

We were able to get around the issue by downloading the github repo, manually building the files and copying them into our project. 

Please include the built files as part of the published npm package.

**Comment by murlimjha** [comment]
Included the package api.js and fixed the aforementioned issue.

Please use the updated SDK.

For any info, please let us know.
Thanks
